@@ -37,6 +37,10 @@ on:
        required: false
        type: string
        default: .
      target:
        description: Build stage to target
        required: false
        type: string
      platforms:
        description: Platforms to build for
        required: false
@@ -104,8 +108,9 @@ jobs:
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ inputs.platforms}}
          context: ${{ inputs.context}}
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.context }}
          target: ${{ inputs.target }}
          builder: ${{ steps.buildx.outputs.name }}
          # it uses github cache API for faster builds:
          # https://github.com/crazy-max/docker-build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
